#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Aug 13 10:40:54 2019

@author: Apple
"""
#extracting twitter hashtag again of india
import tweepy as tw
import pandas as pd
access_token = "1148476189863866368-PYxfmUWkw7iffSXfdKPxMcxYgnCJPv"
access_token_secret = "4fWjalGI52iefSFsUJupwCZ0ASsbgZN8ZOVRZpTOXoluH"
consumer_key = "hrJrzflXRMi9b2In6TasctDho"
consumer_secret = "LrAe6Y5UIGQ9PAKuRjuJ6Evle8LbZJPma99311ljWtnZXcRvnd"
auth = tw.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tw.API(auth)
tweets=api.search(q="football",count=10000,since="2019-01-01");
message=[]
print(tweets)
for tweet in tweets:
    message.append(tweet.text)
df=pd.DataFrame({'Message':message})
df.to_csv(r"/Users/Apple/Desktop/football_tweets.csv")
print(df)